### ISSUE TITLE
The code is wiping out every files in my computer. 

### ISSUE THREAD

**Issue by Yzchen1994** [iamnewton/git-utils#5]
## Because of this line: 
# Remove any untracked files

printf "%s┃%s Removing any untracked files...%s\n" "$(tput setaf 6)" "$(tput sgr0 ; tput setaf 7)" "$(tput sgr0)"
## Console output: 

$ bash -c "$(curl -#fL raw.github.com/chrisopedia/git-utils/go/install)"
###### ################################################################## 100.0%

⚠ Warning: No /usr/local/opt/git-utils found!
┃ Creating directory at /usr/local/opt/git-utils...
mkdir: /usr/local/opt/git-utils: Permission denied
┃ Downloading repository to /tmp directory...
###### ################################################################## 100.0%

┃ Extracting files to /usr/local/opt/git-utils...
tar: could not chdir to '/usr/local/opt/git-utils'

┃ Removing tarball from /tmp directory...
✓ Success: /usr/local/opt/git-utils created, repository downloaded and extracted.
bash: line 38: cd: /usr/local/opt/git-utils: No such file or directory
┃ Initializing git repository...
Initialized empty Git repository in /Users/****/.git/
┃ Adding https://github.com/chrisopedia/git-utils.git as origin...
┃ Downloading changes from origin...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), done.
From https://github.com/chrisopedia/git-utils
- branch            master     -> FETCH_HEAD
- [new branch]      master     -> origin/master
  ┃ Resetting index & working tree to fetched HEAD...
  HEAD is now at f0bd719 Create initial library
  ┃ Removing any untracked files...
  Removing .AndroidStudio2.1/
  Removing .CFUserTextEncoding
  Skipping repository .Trash/careteam
  Skipping repository .Trash/dh-form-builder
  Removing .Trash/.DS_Store
  Removing .Trash/Photo Sep 27, 1 03 53 AM.jpg
  Removing .Trash/Photo Sep 27, 1 58 11 AM.jpg
  Removing .Trash/Photo Sep 27, 2 11 06 AM.jpg
  Removing .Trash/Sublime Text (3124).app
  Removing .Xauthority
  Removing .android/
  Removing .anyconnect
  Removing .bash_history
  Removing .bash_sessions/
  Removing .cache/
  Removing .config/
  Removing .cups/
  Removing .dropbox/
  Removing .eclipse/
  Removing .emulator_console_auth_token
  Removing .gitconfig
  Removing .gradle/

**Comment by chrisopedia** [comment]
Sorry to get back to you @Yzchen1994 so late.  Can you provide me more details please? Whats the OS you're on (type and version).

**Comment by iamnewton** [comment]
this looks like some issues with folder permissions, but closing as stale; if there are any issues, please reach out and i'll reopen
